CREATE USER C##Maksim IDENTIFIED BY Passw0rd DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO C##Maksim
GRANT CREATE TABLE TO C##Maksim
GRANT CREATE PROCEDURE TO C##Maksim
GRANT CREATE TRIGGER TO C##Maksim
GRANT CREATE VIEW TO C##Maksim
GRANT CREATE SEQUENCE TO C##Maksim

SELECT * FROM DBA_USERS;