package by.trjava.task02.entity.criteria;

public final class SearchCriteria {

    private SearchCriteria() {

    }

    public static enum PassengerPlane {
        ID, MANUFACTURER, MODEL_NAME, MAX_SPEED, RACTICAL_CEILING,
        PRACTICAL_RANGE, LENGTH, HEIGHT, FUSELAGE_WIDTH, CREW,
        PASSENGER_CAPACITY, CARGO_CAPACITY, CRUISING_SPEED, EMPTY_WEIGHT,
        TANK_CAPACITY, FUEL_CONSUMPTION, CABIN_WIDTH, AMOUNT_OF_SEATS_IN_ROW,
        LUGGAGE_SHELF_VOLUME
    }

    public static enum CargoPlane {
        ID, MANUFACTURER, MODEL_NAME, MAX_SPEED, RACTICAL_CEILING,
        PRACTICAL_RANGE, LENGTH, HEIGHT, FUSELAGE_WIDTH, CREW,
        PASSENGER_CAPACITY, CARGO_CAPACITY, CRUISING_SPEED, EMPTY_WEIGHT,
        TANK_CAPACITY, FUEL_CONSUMPTION, CARGO_COMPARTMENT_LENGTH, MAX_PAYLOAD
    }

    public static enum MailPlane {
        ID, MANUFACTURER, MODEL_NAME, MAX_SPEED, RACTICAL_CEILING,
        PRACTICAL_RANGE, LENGTH, HEIGHT, FUSELAGE_WIDTH, CREW,
        PASSENGER_CAPACITY, CARGO_CAPACITY, CRUISING_SPEED, EMPTY_WEIGHT,
        TANK_CAPACITY, FUEL_CONSUMPTION, MAX_MAIL_CONTAINERS_AMOUNT
    }
}
